---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  variable_files: 
    - ./terraform.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      controls:
        - bucket_check
        - file_check
        - http_test

platforms:
  - name: terraform

suites:
  - name: kt_suite
